#requires -Version 5.1
<#
    Turns lab.config.json into a shell file the guests can read.

    The host scripts dot-source LabConfig.ps1 and read the JSON directly. The guest scripts
    cannot: they run inside a VM that has no access to the repository. So the addresses, the
    hostnames and the Wazuh version used to be written a second time, by hand, inside
    install-manager.sh and install-agent.sh. Changing the subnet meant changing both, and
    nothing would have told you if you had missed one.

    This writes those values once, as POSIX shell assignments. The seed builder copies the file
    into the VM, cloud-init drops it at /etc/wazuh-lab/lab.env, and each guest script sources it.

    Every guest script keeps a default for each value, so copying one script to a machine by hand
    still works. The defaults are the shipped subnet. If you change lab.config.json and then hand
    copy a script without the env file, you get the shipped subnet rather than a silent failure,
    and the script prints which one it used.

        .\Write-GuestConfig.ps1                 # writes .lab-secrets\seeds\lab.env
        .\Write-GuestConfig.ps1 -Stdout         # prints it instead, for a diff
#>
[CmdletBinding()]
param(
    [ValidateSet('lean', 'full')][string]$Profile,
    [string]$Path,
    [switch]$Stdout
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'LabConfig.ps1')

$config = if ($Profile) { Get-LabConfig -Profile $Profile } else { Get-LabConfig }
$vms    = if ($Profile) { Get-LabVms -Profile $Profile }    else { Get-LabVms }
$active = $config.profile

function Get-LabVmField {
    <#
        One field of one VM, or an empty string when the profile does not build that VM.

        The lean profile has no Windows endpoint. Its address must still be defined, as an empty
        value rather than a missing variable, because the guest scripts run under "set -u" and an
        unset variable is a fatal error there.
    #>
    param([string]$Name, [string]$Field)
    if ($vms.Contains($Name)) { return [string]$vms[$Name].$Field }
    return ''
}

# Everything that is not the manager is an agent, and the ufw rules on the manager are written
# from this list rather than from three literal addresses.
$agentAddresses = @(
    foreach ($name in $vms.Keys) {
        if ($name -ne 'WAZUH-MANAGER') { $vms[$name].Address }
    }
) -join ' '

$values = [ordered]@{
    LAB_PROFILE           = $active
    LAB_BACKEND           = $config.backend
    LAB_NETWORK_NAME      = $config.network.name
    LAB_SUBNET            = $config.network.subnet
    LAB_GATEWAY           = $config.network.gateway
    LAB_PREFIX_LENGTH     = [string]$config.network.prefixLength
    LAB_DNS               = ($config.network.dns -join ' ')
    LAB_GUEST_USER        = $config.guest.user
    LAB_TIMEZONE          = $config.guest.timezone
    LAB_MANAGER_HOST      = Get-LabVmField 'WAZUH-MANAGER' 'Hostname'
    LAB_MANAGER_ADDR      = Get-LabVmField 'WAZUH-MANAGER' 'Address'
    LAB_LINUX_HOST        = Get-LabVmField 'WAZUH-LINUX' 'Hostname'
    LAB_LINUX_ADDR        = Get-LabVmField 'WAZUH-LINUX' 'Address'
    LAB_WINDOWS_HOST      = Get-LabVmField 'WAZUH-WIN' 'Hostname'
    LAB_WINDOWS_ADDR      = Get-LabVmField 'WAZUH-WIN' 'Address'
    LAB_AGENT_ADDRS       = $agentAddresses
    LAB_WAZUH_VERSION     = $config.wazuh.version
    LAB_WAZUH_PKG_VERSION = $config.wazuh.packageVersion
    LAB_INDEXER_HEAP_MB   = [string]$config.profiles.$active.indexerHeapMb
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Generated by setup\Write-GuestConfig.ps1 from lab.config.json. Do not edit here.')
$lines.Add('# Sourced by the guest install scripts. Edit lab.config.json and regenerate.')
foreach ($key in $values.Keys) {
    $value = [string]$values[$key]
    if ($value -match "[`"`$\\``]") { throw "Value for $key contains a character the shell would reinterpret: $value" }
    $lines.Add(('{0}="{1}"' -f $key, $value))
}

# LF endings and no BOM. A CRLF here becomes a carriage return inside every variable the guest
# reads, which turns an address into one that does not resolve and an error that reads as a
# network fault rather than a line ending.
$text = ($lines -join "`n") + "`n"

if ($Stdout) {
    Write-Output $text
    return
}

$target = if ($Path) { $Path } else { Join-Path (Get-LabPath Seeds) 'lab.env' }
$dir = Split-Path -Parent $target
if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
[IO.File]::WriteAllText($target, $text, (New-Object Text.UTF8Encoding $false))
Write-Output ("Wrote {0} values for the {1} profile to {2}" -f $values.Count, $active, $target)
